import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  // ignore: avoid_renaming_method_parameters
  Future<Map<String, dynamic>> load(String fullPath, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "welcome": "مرحبا في ",
    "login": "تسجيل الدخول",
    "login_google": "تسجيل باستخدام جوجل",
    "signup": "تسجيل",
    "no_account": "ليس لديك حساب؟",
    "email": "البريد الالكتروني",
    "password": "كلمة المرور",
    "forget_pass": "نسيت كلمه المرور؟",
    "name": "الاسم",
    "all_heigh": "كل المراجعات",
    "review": "مراجعة",
    "add_heigh": "اضافة مراجعة",
    "camera": "كاميرا",
    "text": "نص",
    "heighlight": "مراجعة",
    "book": "الكتب",
    "top": "الافضل",
    "all_cate": "كل الفئات",
    "search": "ابحث",
    "recent_search": "البحث الحديث",
    "write_txt": "اكتب النص هنا",
    "book_name": "اسم الكتاب",
    "none": "لا يوجد",
    "done": "تم",
    "setting": "الاعدادات",
    "personal": "شخصي",
    "save": "حفظ",
    "cancel": "الغاء",
    "change_name": "غير اسمك",
    "change_pass": "غير كلمة المرور",
    "app": "التطبيق",
    "dark_mode": "الوضع الليلي",
    "lang": "اللغة",
    "unknown": "غير معروف",
    "me": "انا",
    "render_image": "استخراج صوره",
    "customize": "تعديل",
    "login_success": "تم تسجيل الدخول بنجاح",
    "email_validation": "ادخل بريد صالح",
    "password_validation": "كلمة المرور يجب ان تكون 8 احرف علي الاقل",
    "name_validation": "ادخل اسم صالح",
    "forget_password_txt":
        "اكتب البريد الالكتروني الخاص بك لتتمكن من اعاده تعيين كلمه المرور",
    "send": "ارسل",
    "height": "الطول",
    "position": "الموضع",
    "txt_color": "لون النص",
    "pick_color": "لون اخر",
    "internet_connection": "لا يوجد اتصال بالانترنت رجاءً تفقد الاتصال",
    "no_heighLight": "لا يوجد مراجعات ",
    "no_more_heigh": "لا يوجد مراجعات اخري",
    "txtfrom_field_validation": "هذا الحقل لا يمكن ان يكون فارغ",
    "edit": "تعديل",
    "add_heigh_error": "يجب عليك اختيار الكتاب و ان لم يكن موجود اضغط لا يوجد",
    "add_txt_save": "اضف نص لكي يحفظ",
    "book_validation": "يجب اختيار كتاب ان وجد",
    "unknown_discription": "وصف هذا الكتاب غير معروف ",
    "num_page": "عدد الصفحات",
    "cate": "الفئة",
    "rating": "التقييم",
    "discription": "الوصف",
    "price": "السعر",
    "lets_read": "هيا اقرأ",
    "confirm_email": "اكد البريد الالكتروني",
    "confirm_email_validation": "البريد الالكتروني غير مطابق للبريد الحالي",
    "send_email": "تم الارسال لبريدك الالكتروني",
    "system_mode": "النظام",
    "dark": "ليلي",
    "light": "الضوء",
    "clear": "حذف",
    "clear_tile": "حذف تاريخ البحث",
    "ensure_dis": "سيتم حذف جميع سجلات بحثك و لا يمكن استرجاعها",
    "ensure": "هل انت متأكد؟",
    "theme": "السمات",
    "change_theme": "تغيير السمه",
    "logout": "تسجيل الخروج",
    "gallery": "المعرض",
    "good_job": "عمل رائع",
    "review_discovery_title": "انقر لتمريرها",
    "review_discovery_dis": " يمكنك النقر علي الكارت لتمريره و اظهار الذي يليه",
    "heughlight_discovery_title": "يمكنك اضافه نص",
    "heughlight_discovery_dis":
        "عند اضافه النص سيظهر في قائمة الكروت و عندها يمكنك تذكره",
    "heughlight_discovery_cam_title": "يمكنك اضافه نص بالكاميرا",
    "heughlight_discovery_cam_dis":
        "يمكنك اضافه نص جديد بالكاميرا او المعرض ولكن لاحظ هذه الميزه تعمل حاليا علي اللغه الانجليزيه",
    "searchBook_discovery_title": "البحث عن الكتب",
    "searchBook_discovery_dis":
        "هنا يوجد بعض الكتب و يمكنك ايضا البحث عم الكتاب الذي تريده"
  };
  static const Map<String, dynamic> en = {
    "welcome": "Welcome to",
    "login": "LOGIN",
    "login_google": "Sign up with Google",
    "signup": "Sign up",
    "no_account": "Don't have an account?",
    "email": "Email",
    "password": "Password",
    "forget_pass": "Forget Passwrod?",
    "name": "Name",
    "all_heigh": "All HeighLights",
    "review": "Review",
    "add_heigh": "Add HeighLight",
    "camera": "Camera",
    "text": "Text",
    "heighlight": "HeighLight",
    "book": "Books",
    "top": "Top",
    "all_cate": "All Categories",
    "search": "Search",
    "recent_search": "Recent Search",
    "write_txt": "Write Text Here",
    "book_name": "Book Name",
    "none": "None",
    "done": "Done",
    "setting": "Settings",
    "personal": "Personal",
    "save": "Save",
    "cancel": "Cancel",
    "change_name": "Change your name",
    "change_pass": "Change Password",
    "app": "App",
    "dark_mode": "Dark Mode",
    "lang": "Language",
    "unknown": "Unknown",
    "me": "Me",
    "render_image": "redner Image",
    "customize": "Customize",
    "login_success": "Log in Successfully",
    "email_validation": "Enter a valid Email",
    "password_validation": "Password must be at least 8 char",
    "name_validation": "Enter a valid Name",
    "forget_password_txt":
        "Write down their your email to reset your password.",
    "send": "send",
    "height": "height",
    "position": "Position",
    "txt_color": "Text Color",
    "pick_color": "Pick Color",
    "internet_connection": "There is no internet please check connection",
    "no_heighLight": "No Heighlights found",
    "no_more_heigh": "no more heightlights",
    "txtfrom_field_validation": "This Field can not be empty",
    "edit": "Edit",
    "add_heigh_error":
        "You should Click on your book if it is not exist click none",
    "add_txt_save": "Add some text to save",
    "book_validation": "You shoud choose book if exist if not click none",
    "unknown_discription": "This book description is unknown",
    "num_page": "Number of Pages",
    "cate": "Category",
    "rating": "Rating",
    "discription": "Discription",
    "price": "Price",
    "lets_read": "Let's Read",
    "confirm_email": "Confirm Email",
    "confirm_email_validation": "Email is not match your current Email",
    "send_email": "Email has been send",
    "system_mode": "System",
    "dark": "Dark",
    "light": "Light",
    "clear": "Clear",
    "clear_tile": "Clear search history",
    "ensure_dis":
        "You will remove all your book search history you can't get it back",
    "ensure": "Are you sure?",
    "theme": "Themes",
    "change_theme": "Change Theme",
    "logout": "Logout",
    "gallery": "Gallery",
    "good_job": "Good Job",
    "review_discovery_title": "Tap to Swip",
    "review_discovery_dis":
        "You can Tap to swip between cards and memorize your Areading cards",
    "heughlight_discovery_title": "Add new Areading Card",
    "heughlight_discovery_dis":
        "You can Add Areading card Here to memorize it again",
    "heughlight_discovery_cam_title": "Add new Areading Card by camera",
    "heughlight_discovery_cam_dis":
        "You can Add Areading card here from your camera or gallery but notes it's working currently on English  only",
    "searchBook_discovery_title": "Searching For books!!",
    "searchBook_discovery_dis":
        "Here is the book section where you can find some books and You can search for any book you need and have more information about it"
  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "ar": ar,
    "en": en
  };
}
